        
hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: ["main"]
    resource_owners:
        facebook:
            type: facebook
            client_id: 1082234545205978
            client_secret: 7ceda4cf17ce66bb40117433c3b94d18
            scope: "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email,picture.type(square)"
            paths:
                email:          email
                profilepicture: picture.data.url
            options:
                csrf: true
                display: popup
    connect:
        account_connector: my.custom.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:    facebook_id         
           